### ISSUE TITLE
ตอน EnemyShip ตายขึ้น error นี้

### ISSUE THREAD

**Issue by Terix1flow** [ZerotoHeroDaimaiKub/AsteroidX#22]
Exception in thread "JavaFX Application Thread" java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1096)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1050)
	at se233.asterioddemo/se233.asterioddemo.GameEntityManager.checkPlayerBulletEnemyCollisions(GameEntityManager.java:328)
	at se233.asterioddemo/se233.asterioddemo.GameEntityManager.checkCollisions(GameEntityManager.java:253)
	at se233.asterioddemo/se233.asterioddemo.AsteroidGame.checkCollisions(AsteroidGame.java:314)
	at se233.asterioddemo/se233.asterioddemo.AsteroidGame.updateGame(AsteroidGame.java:227)
	at se233.asterioddemo/se233.asterioddemo.AsteroidGame$1.handle(AsteroidGame.java:147)
	at javafx.graphics@21.0.2/javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$0(AnimationTimer.java:58)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21.0.2/javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:57)
	at javafx.graphics@21.0.2/com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(AbstractPrimaryTimer.java:356)
	at javafx.graphics@21.0.2/com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(AbstractPrimaryTimer.java:266)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:588)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:572)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:565)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
	at javafx.graphics@21.0.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1570) 

![image](https://github.com/user-attachments/assets/4dbe4e72-8fc8-4c14-a7df-845fe617b2bc)

**Comment by NotPrab** [comment]
แก้ละ
