### ISSUE TITLE
Error ตอน check collisions ของ checkPlayerBulletAsteroidCollisions 

### ISSUE THREAD

**Issue by NotPrab** [ZerotoHeroDaimaiKub/AsteroidX#29]
[2024-10-28 17:08:53] [INFO] se233.asterioddemo.AsteroidGame startGame - Game started.
[2024-10-28 17:08:58] [INFO] se233.asterioddemo.GameEntityManager checkPlayerBulletAsteroidCollisions - Asteroid destroyed! Score: 2
Exception in thread "JavaFX Application Thread" java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049)
	at se233.asterioddemo@1.0-SNAPSHOT/se233.asterioddemo.GameEntityManager.updateAndDrawAsteroids(GameEntityManager.java:210)
	at se233.asterioddemo@1.0-SNAPSHOT/se233.asterioddemo.AsteroidGame.updateGame(AsteroidGame.java:217)
	at se233.asterioddemo@1.0-SNAPSHOT/se233.asterioddemo.AsteroidGame$1.handle(AsteroidGame.java:157)
	at javafx.graphics@21.0.2/javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$0(AnimationTimer.java:58)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21.0.2/javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:57)
	at javafx.graphics@21.0.2/com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(AbstractPrimaryTimer.java:356)
	at javafx.graphics@21.0.2/com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(AbstractPrimaryTimer.java:266)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:588)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:572)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:565)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
	at javafx.graphics@21.0.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)
[2024-10-28 17:09:01] [WARNING] se233.asterioddemo.GameEntityManager checkPlayerAsteroidCollisions - Player hit by Asteroid! Lives remaining: 2

**Comment by NotPrab** [comment]
fix
